
######### DEFAULT #########
tokenLength: 50
activationCodeLength: 4
referrerIdLength: 50

recaptchaSecretKey: XXX

server:
    port: 8102
    contextPath: /slounge
#logging:
#  level:
#    org:
#      hibernate:
#        SQL:  DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slounge?useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true
        username: root
        password: root
        max-active: 20
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

##########  PROD   #############


spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/slounge?useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: K8y348Q
        max-active: 20
